# Generated by Django 4.1 on 2023-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='picture',
        ),
        migrations.AddField(
            model_name='animal',
            name='details',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
